package e

const (
	CACHE_ARTICLE      = "ARTICLE"
	CACHE_TAG          = "TAG"
	STORY_TAG          = "STORY"
	STORY_TAG_HOT_RANK = "STORY_HOT_RANK_TWO"
	CATEGORY_STORY     = "CATEGORY_STORY"
	CHAPTER_CONTENT    = "CHAPTER_CONTENT"
	BOOK_INFO          = "BOOK_INFO"
)
