// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: chapter.proto

//包名，通过protoc生成时go文件时

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//手机类型m
//枚举类型第一个字段必须为0
type ChapterProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	HasContent string `protobuf:"bytes,3,opt,name=HasContent,proto3" json:"HasContent,omitempty"`
}

func (x *ChapterProto) Reset() {
	*x = ChapterProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chapter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChapterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterProto) ProtoMessage() {}

func (x *ChapterProto) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterProto.ProtoReflect.Descriptor instead.
func (*ChapterProto) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{0}
}

func (x *ChapterProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChapterProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChapterProto) GetHasContent() string {
	if x != nil {
		return x.HasContent
	}
	return ""
}

type ChaptersProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChaptersProto []*ChapterProto `protobuf:"bytes,1,rep,name=chaptersProto,proto3" json:"chaptersProto,omitempty"`
}

func (x *ChaptersProto) Reset() {
	*x = ChaptersProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chapter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChaptersProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaptersProto) ProtoMessage() {}

func (x *ChaptersProto) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaptersProto.ProtoReflect.Descriptor instead.
func (*ChaptersProto) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{1}
}

func (x *ChaptersProto) GetChaptersProto() []*ChapterProto {
	if x != nil {
		return x.ChaptersProto
	}
	return nil
}

var File_chapter_proto protoreflect.FileDescriptor

var file_chapter_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x52, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x48,
	0x61, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x48, 0x61, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x4b, 0x0a, 0x0d, 0x43,
	0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3a, 0x0a, 0x0d,
	0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x68, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chapter_proto_rawDescOnce sync.Once
	file_chapter_proto_rawDescData = file_chapter_proto_rawDesc
)

func file_chapter_proto_rawDescGZIP() []byte {
	file_chapter_proto_rawDescOnce.Do(func() {
		file_chapter_proto_rawDescData = protoimpl.X.CompressGZIP(file_chapter_proto_rawDescData)
	})
	return file_chapter_proto_rawDescData
}

var file_chapter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chapter_proto_goTypes = []interface{}{
	(*ChapterProto)(nil),  // 0: models.ChapterProto
	(*ChaptersProto)(nil), // 1: models.ChaptersProto
}
var file_chapter_proto_depIdxs = []int32{
	0, // 0: models.ChaptersProto.chaptersProto:type_name -> models.ChapterProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chapter_proto_init() }
func file_chapter_proto_init() {
	if File_chapter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chapter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChapterProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chapter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChaptersProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chapter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chapter_proto_goTypes,
		DependencyIndexes: file_chapter_proto_depIdxs,
		MessageInfos:      file_chapter_proto_msgTypes,
	}.Build()
	File_chapter_proto = out.File
	file_chapter_proto_rawDesc = nil
	file_chapter_proto_goTypes = nil
	file_chapter_proto_depIdxs = nil
}
